    # preview.musiver.cn html-preview begin
    server {
        listen 443 ssl;
        server_name preview.musiver.cn;

        acme_certificate    letsencrypt;
        ssl_certificate     $acme_certificate;
        ssl_certificate_key $acme_certificate_key;
        ssl_certificate_cache max=2;

        client_max_body_size 25m;

        location / {
            proxy_pass http://127.0.0.1:7849;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 120s;
        }
    }
    # preview.musiver.cn html-preview end
